services:
  jupyterlab:
    image: wngfra/dl-jupyterlab:da
    ports:
      - 8888:8888
    volumes:
      - ../FabricSlide:/workdir/FabricSlide
    container_name: data-analysis
    ulimits:
      memlock: -1
    shm_size: '8gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
