services:
  jupyter-notebook:
    command: python -c "import torch as T;print(T.cuda.is_available())"
    image: wngfra/ros2cuda:pytorch-notebook
    ports:
        - 8888:8888
    volumes:
      - ../FabricSlide:/workspace/FabricSlide
    container_name: pytorch-notebook-container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
