services:
  jupyter-notebook:
    image: wngfra/dl-jupyterlab:da
    ports:
        - 8888:8888
    volumes:
      - ../FabricSlide:/workspace/FabricSlide
    container_name: data-analysis
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
