services:
  jupyter-notebook:
    image: wngfra/ros2cuda:pytorch-notebook
    ports:
        - 8888:8888
    volumes:
      - ../FabricSlide:/workspace/FabricSlide
    container_name: pytorch-notebook-container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
